using System.Collections;
using System.Collections.Generic;

using UnityEngine;

public enum GameDifficulty
{
    DIFFICULTY_NONE,
    DIFFICULTY_EASY,
    DIFFICULTY_NORMAL,
    DIFFICULTY_HARD,
    DIFFICULTY_LUNATIC,
    DIFFICULTY_EXTRA,
}

public enum GameMode
{
    GAMEMODE_NONE,
    GAMEMODE_TITLE,
    GAMEMODE_MAINGAME,
    GAMEMODE_ENDING,
    GAMEMODE_STAFFROLL,
    GAMEMODE_RANKING,
    GAMEMODE_PRACTICE,
    GAMEMODE_REPLAY,
}

public enum GamePracticeStage
{
    GAMEPRACTICESTAGE_NONE,
    GAMEPRACTICESTAGE_STAGE1,
    GAMEPRACTICESTAGE_STAGE2,
    GAMEPRACTICESTAGE_STAGE3,
    GAMEPRACTICESTAGE_STAGE4,
    GAMEPRACTICESTAGE_STAGE5,
    GAMEPRACTICESTAGE_STAGE6,
}

public enum GameGrade
{
    GAMEGRADE_NONE,
    GAMEGRADE_F,
    GAMEGRADE_D,
    GAMEGRADE_C,
    GAMEGRADE_B,
    GAMEGRADE_A,
    GAMEGRADE_S,
}

public enum EnemyType
{
    ENEMYTYPE_NONE,
    ENEMYTYPE_SMINION,
    ENEMYTYPE_MMINION,
    ENEMYTYPE_LMINION,
    ENEMYTYPE_BOSS,
}

public enum BulletType
{
    BULLETTYPE_NONE,
    BULLETTYPE_EMPTY,
    BULLETTYPE_NORMAL,
    BULLETTYPE_LASER_HOLD,
    BULLETTYPE_LASER_MOVE,
}

public enum BulletReflectState
{
    BULLETREFLECTSTATE_NONE,
    BULLETREFLECTSTATE_NORMAL,
    BULLETREFLECTSTATE_CONTAINBOTTOM,
}

public enum BulletSpeedState
{
    BULLETSPEEDSTATE_NONE,
    BULLETSPEEDSTATE_NORMAL,
    BULLETSPEEDSTATE_ACCELERATING,
    BULLETSPEEDSTATE_DECELERATING,
    BULLETSPEEDSTATE_LOOP,
    BULLETSPEEDSTATE_LOOPONCE,
}

public enum BulletRotateState
{
    BULLETROTATESTATE_NONE,
    BULLETROTATESTATE_NORMAL,
    BULLETROTATESTATE_LIMIT,
    BULLETROTATESTATE_ROTATEAROUND,
    BULLETROTATESTATE_LOOKAT,
    BULLETROTATESTATE_LOOPSIN,
    BULLETROTATESTATE_LOOPCOS,
}