using System.Collections;
using System.Collections.Generic;

using UnityEngine;

public enum GameDifficulty
{
    DIFFICULTY_NONE,
    DIFFICULTY_EASY,
    DIFFICULTY_NORMAL,
    DIFFICULTY_HARD,
    DIFFICULTY_LUNATIC,
    DIFFICULTY_EXTRA,
}

public enum GameMode
{
    GAMEMODE_NONE,
    GAMEMODE_TITLE,
    GAMEMODE_MAINGAME,
    GAMEMODE_ENDING,
    GAMEMODE_STAFFROLL,
    GAMEMODE_RANKING,
    GAMEMODE_PRACTICE,
    GAMEMODE_REPLAY,
}

public enum GamePracticeStage
{
    GAMEPRACTICESTAGE_NONE,
    GAMEPRACTICESTAGE_STAGE1,
    GAMEPRACTICESTAGE_STAGE2,
    GAMEPRACTICESTAGE_STAGE3,
    GAMEPRACTICESTAGE_STAGE4,
    GAMEPRACTICESTAGE_STAGE5,
    GAMEPRACTICESTAGE_STAGE6,
}

public enum GameGrade
{
    GAMEGRADE_NONE,
    GAMEGRADE_F,
    GAMEGRADE_D,
    GAMEGRADE_C,
    GAMEGRADE_B,
    GAMEGRADE_A,
    GAMEGRADE_S,
}